In [468]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [469]:
data=pd.read_csv('training_set_features.csv')

In [470]:
data

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0                  0          1.0            0.0                        0.0   
1                  1          3.0            2.0                        0.0   
2                  2          1.0            1.0                        0.0   
3                  3          1.0            1.0                        0.0   
4                  4          2.0            1.0                        0.0   
...              ...          ...            ...                        ...   
26702          26702          2.0            0.0                        0.0   
26703          26703          1.0            2.0                        0.0   
26704          26704          2.0            2.0                        0.0   
26705          26705          1.0            1.0                        0.0   
26706          26706          0.0            0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
2                       1.0                   0.0                    0.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   1.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
2                              0.0                      0.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
...                            ...                      ...   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26704                          1.0                      0.0   
26705                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  ...  rent_or_own   employment_status  \
0                        1.0  ...          Own  Not in Labor Force   
1                        1.0  ...         Rent            Employed   
2                        0.0  ...          Own            Employed   
3                        0.0  ...         Rent  Not in Labor Force   
4                        1.0  ...          Own            Employed   
...                      ...  ...          ...                 ...   
26702                    0.0  ...          Own  Not in Labor Force   
26703                    0.0  ...         Rent            Employed   
26704                    1.0  ...          Own                 NaN   
26705                    NaN  ...         Rent            Employed   
26706                    0.0  ...          Own  Not in Labor Force   

       hhs_geo_region                census_msa  household_adults  \
0            oxchjgsf                   Non-MSA               0.0   
1            bhuqouqj  MSA, Not Principle  City               0.0   
2            qufhixun  MSA, Not Principle  City               2.0   
3            lrircsnp       MSA, Principle City               0.0   
4            qufhixun  MSA, Not Principle  City               1.0   
...               ...                       ...               ...   
26702        qufhixun                   Non-MSA               0.

In [471]:
data=data.drop('hhs_geo_region',axis=1)

In [472]:
data=data.drop('employment_industry',axis=1)

In [473]:
data=data.drop("employment_occupation",axis=1)

In [474]:
data

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0                  0          1.0            0.0                        0.0   
1                  1          3.0            2.0                        0.0   
2                  2          1.0            1.0                        0.0   
3                  3          1.0            1.0                        0.0   
4                  4          2.0            1.0                        0.0   
...              ...          ...            ...                        ...   
26702          26702          2.0            0.0                        0.0   
26703          26703          1.0            2.0                        0.0   
26704          26704          2.0            2.0                        0.0   
26705          26705          1.0            1.0                        0.0   
26706          26706          0.0            0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
2                       1.0                   0.0                    0.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   1.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
2                              0.0                      0.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
...                            ...                      ...   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26704                          1.0                      0.0   
26705                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  ...     sex             income_poverty  \
0                        1.0  ...  Female              Below Poverty   
1                        1.0  ...    Male              Below Poverty   
2                        0.0  ...    Male  <= $75,000, Above Poverty   
3                        0.0  ...  Female              Below Poverty   
4                        1.0  ...  Female  <= $75,000, Above Poverty   
...                      ...  ...     ...                        ...   
26702                    0.0  ...  Female  <= $75,000, Above Poverty   
26703                    0.0  ...    Male  <= $75,000, Above Poverty   
26704                    1.0  ...  Female                        NaN   
26705                    NaN  ...  Female  <= $75,000, Above Poverty   
26706                    0.0  ...    Male  <= $75,000, Above Poverty   

       marital_status  rent_or_own   employment_status  \
0         Not Married          Own  Not in Labor Force   
1         Not Married         Rent            Employed   
2         Not Married          Own            Employed   
3         Not Married         Rent  Not in Labor Force   
4             Married          Own            Employed   
...               ...          ...                 ...   
26702     Not Married          Own  Not in Labor Force   
26703     Not Married         Rent            Employed   
2

In [475]:
data1=data.copy()

In [476]:
print(data.isnull().values.sum())

33962


In [477]:
data.set_index(['respondent_id'], inplace=True)

In [478]:
data

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
respondent_id                                                          
0                      1.0            0.0                        0.0   
1                      3.0            2.0                        0.0   
2                      1.0            1.0                        0.0   
3                      1.0            1.0                        0.0   
4                      2.0            1.0                        0.0   
...                    ...            ...                        ...   
26702                  2.0            0.0                        0.0   
26703                  1.0            2.0                        0.0   
26704                  2.0            2.0                        0.0   
26705                  1.0            1.0                        0.0   
26706                  0.0            0.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
0                               0.0                   0.0   
1                               1.0                   0.0   
2                               1.0                   0.0   
3                               1.0                   0.0   
4                               1.0                   0.0   
...                             ...                   ...   
26702                           1.0                   0.0   
26703                           1.0                   0.0   
26704                           1.0                   1.0   
26705                           0.0                   0.0   
26706                           1.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
0                                0.0                          0.0   
1                                1.0                          0.0   
2                                0.0                          0.0   
3                                1.0                          1.0   
4                                1.0                          1.0   
...                              ...                          ...   
26702                            0.0                          0.0   
26703                            1.0                          0.0   
26704                            1.0                          1.0   
26705                            0.0                          0.0   
26706                            0.0                          0.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
0                                  1.0                    1.0   
1                                  1.0                    1.0   
2                                  0.0                    0.0   
3                                  0.0                    0.0   
4                                  0.0                    1.0   
...                                ...                    ...   
26702                              1.0                    0.0   
26703                              0.0                    0.0   
26704                              0.0                    1.0   
26705                              0.0                    NaN   
26706                              0.0                    0.0   

               doctor_recc_xyz  ...     sex             income_poverty  \
respondent_id                   ...                                      
0                          0.0  ...  Female              Below Poverty   
1                          0.0  ...    Male              Below Poverty   
2                          NaN  ...    Male  <= $75,000, Above Poverty   
3                          0.0  ...  Female              Below Poverty   
4                          0.0  ...  Female  <= $75,000, Above Poverty   
...                   

In [479]:
x=data.iloc[:,:]

In [480]:
y1=data.iloc[:,-1]
y1

respondent_id
0        0
1        1
2        0
3        1
4        0
        ..
26702    0
26703    0
26704    1
26705    0
26706    0
Name: seasonal_vaccine, Length: 26707, dtype: int64

In [481]:
y2=data.iloc[:,-2]
y2

respondent_id
0        0
1        0
2        0
3        0
4        0
        ..
26702    0
26703    0
26704    0
26705    0
26706    0
Name: xyz_vaccine, Length: 26707, dtype: int64

In [482]:
x

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
respondent_id                                                          
0                      1.0            0.0                        0.0   
1                      3.0            2.0                        0.0   
2                      1.0            1.0                        0.0   
3                      1.0            1.0                        0.0   
4                      2.0            1.0                        0.0   
...                    ...            ...                        ...   
26702                  2.0            0.0                        0.0   
26703                  1.0            2.0                        0.0   
26704                  2.0            2.0                        0.0   
26705                  1.0            1.0                        0.0   
26706                  0.0            0.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
0                               0.0                   0.0   
1                               1.0                   0.0   
2                               1.0                   0.0   
3                               1.0                   0.0   
4                               1.0                   0.0   
...                             ...                   ...   
26702                           1.0                   0.0   
26703                           1.0                   0.0   
26704                           1.0                   1.0   
26705                           0.0                   0.0   
26706                           1.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
0                                0.0                          0.0   
1                                1.0                          0.0   
2                                0.0                          0.0   
3                                1.0                          1.0   
4                                1.0                          1.0   
...                              ...                          ...   
26702                            0.0                          0.0   
26703                            1.0                          0.0   
26704                            1.0                          1.0   
26705                            0.0                          0.0   
26706                            0.0                          0.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
0                                  1.0                    1.0   
1                                  1.0                    1.0   
2                                  0.0                    0.0   
3                                  0.0                    0.0   
4                                  0.0                    1.0   
...                                ...                    ...   
26702                              1.0                    0.0   
26703                              0.0                    0.0   
26704                              0.0                    1.0   
26705                              0.0                    NaN   
26706                              0.0                    0.0   

               doctor_recc_xyz  ...     sex             income_poverty  \
respondent_id                   ...                                      
0                          0.0  ...  Female              Below Poverty   
1                          0.0  ...    Male              Below Poverty   
2                          NaN  ...    Male  <= $75,000, Above Poverty   
3                          0.0  ...  Female              Below Poverty   
4                          0.0  ...  Female  <= $75,000, Above Poverty   
...                   

In [483]:
x.columns

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'census_msa', 'household_adults',
       'household_children', 'xyz_vaccine', 'seasonal_vaccine'],
      dtype='object')

In [484]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [486]:
x=x.drop('xyz_vaccine',axis=1)

In [487]:
x=x.drop('seasonal_vaccine',axis=1)

In [488]:
x

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
respondent_id                                                          
0                      1.0            0.0                        0.0   
1                      3.0            2.0                        0.0   
2                      1.0            1.0                        0.0   
3                      1.0            1.0                        0.0   
4                      2.0            1.0                        0.0   
...                    ...            ...                        ...   
26702                  2.0            0.0                        0.0   
26703                  1.0            2.0                        0.0   
26704                  2.0            2.0                        0.0   
26705                  1.0            1.0                        0.0   
26706                  0.0            0.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
0                               0.0                   0.0   
1                               1.0                   0.0   
2                               1.0                   0.0   
3                               1.0                   0.0   
4                               1.0                   0.0   
...                             ...                   ...   
26702                           1.0                   0.0   
26703                           1.0                   0.0   
26704                           1.0                   1.0   
26705                           0.0                   0.0   
26706                           1.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
0                                0.0                          0.0   
1                                1.0                          0.0   
2                                0.0                          0.0   
3                                1.0                          1.0   
4                                1.0                          1.0   
...                              ...                          ...   
26702                            0.0                          0.0   
26703                            1.0                          0.0   
26704                            1.0                          1.0   
26705                            0.0                          0.0   
26706                            0.0                          0.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
0                                  1.0                    1.0   
1                                  1.0                    1.0   
2                                  0.0                    0.0   
3                                  0.0                    0.0   
4                                  0.0                    1.0   
...                                ...                    ...   
26702                              1.0                    0.0   
26703                              0.0                    0.0   
26704                              0.0                    1.0   
26705                              0.0                    NaN   
26706                              0.0                    0.0   

               doctor_recc_xyz  ...         education      race     sex  \
respondent_id                   ...                                       
0                          0.0  ...        < 12 Years     White  Female   
1                          0.0  ...          12 Years     White    Male   
2                          NaN  ...  College Graduate     White    Male   
3                          0.0  ...          12 Years     White  Female   
4                          0.0  ...      Some College     White  Female   
...            

In [489]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['rent_or_own']=le.fit_transform(x['rent_or_own'])

In [490]:
x['sex']=le.fit_transform(x['sex'])

In [491]:
x['marital_status']=le.fit_transform(x['marital_status'])

In [492]:
x['income_poverty']=le.fit_transform(x['income_poverty'])

In [493]:
x['census_msa']=le.fit_transform(x['census_msa'])

In [494]:
x.columns.tolist().index('employment_status')

28

In [495]:
x['employment_status']=le.fit_transform(x['employment_status'])

In [496]:
x['race']=le.fit_transform(x['race'])

In [497]:
x['age_group']=le.fit_transform(x['age_group'])

In [498]:
x['education']=le.fit_transform(x['education'])

In [499]:
x.isnull().values.sum()

23219

In [500]:
imputer.fit(x)

SimpleImputer()

In [501]:
x=imputer.transform(x)

In [502]:
x

array([[1., 0., 0., ..., 2., 0., 0.],
       [3., 2., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 2., 0.],
       ...,
       [2., 2., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 2., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [503]:
x_test=pd.read_csv('test_set_features.csv')

In [504]:
x_test

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              26707          2.0            2.0                        0.0   
1              26708          1.0            1.0                        0.0   
2              26709          2.0            2.0                        0.0   
3              26710          1.0            1.0                        0.0   
4              26711          3.0            1.0                        1.0   
...              ...          ...            ...                        ...   
26703          53410          1.0            1.0                        0.0   
26704          53411          3.0            1.0                        0.0   
26705          53412          0.0            1.0                        0.0   
26706          53413          3.0            1.0                        0.0   
26707          53414          2.0            1.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       1.0                   0.0                    1.0   
1                       0.0                   0.0                    0.0   
2                       0.0                   1.0                    1.0   
3                       0.0                   0.0                    0.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   0.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    1.0   
26707                   0.0                   0.0                    1.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              1.0                      0.0   
1                              0.0                      0.0   
2                              1.0                      1.0   
3                              0.0                      0.0   
4                              1.0                      1.0   
...                            ...                      ...   
26703                          0.0                      0.0   
26704                          1.0                      1.0   
26705                          0.0                      0.0   
26706                          0.0                      1.0   
26707                          0.0                      0.0   

       behavioral_touch_face  ...             income_poverty  marital_status  \
0                        1.0  ...                  > $75,000     Not Married   
1                        0.0  ...              Below Poverty     Not Married   
2                        1.0  ...                  > $75,000         Married   
3                        0.0  ...  <= $75,000, Above Poverty         Married   
4                        1.0  ...  <= $75,000, Above Poverty     Not Married   
...                      ...  ...                        ...             ...   
26703                    1.0  ...                        NaN             NaN   
26704                    1.0  ...              Below Poverty         Married   
26705                    0.0  ...              Below Poverty     Not Married   
26706                    0.0  ...  <= $75,000, Above Poverty         Married   
26707                    1.0  ...                        NaN     Not Married   

       rent_or_own   employment_status  hhs_geo_region  \
0             Rent            Employed        mlyzmhmf   
1             Rent            Employed        bhuqouqj   
2              Own            Employed        lrircsnp   
3              Own  Not in Labor Force        lrircsnp   
4              Own            Employed        lzgpxyit   
...            ...                 ...             ...   
26703          NaN   

In [505]:
x_test.isnull().values.sum()

60551

In [506]:
x_test=x_test.drop('hhs_geo_region',axis=1)

In [507]:
x_test=x_test.drop('employment_industry',axis=1)

In [508]:
x_test=x_test.drop('employment_occupation',axis=1)

In [509]:
x_test

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0              26707          2.0            2.0                        0.0   
1              26708          1.0            1.0                        0.0   
2              26709          2.0            2.0                        0.0   
3              26710          1.0            1.0                        0.0   
4              26711          3.0            1.0                        1.0   
...              ...          ...            ...                        ...   
26703          53410          1.0            1.0                        0.0   
26704          53411          3.0            1.0                        0.0   
26705          53412          0.0            1.0                        0.0   
26706          53413          3.0            1.0                        0.0   
26707          53414          2.0            1.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       1.0                   0.0                    1.0   
1                       0.0                   0.0                    0.0   
2                       0.0                   1.0                    1.0   
3                       0.0                   0.0                    0.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   0.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    1.0   
26707                   0.0                   0.0                    1.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              1.0                      0.0   
1                              0.0                      0.0   
2                              1.0                      1.0   
3                              0.0                      0.0   
4                              1.0                      1.0   
...                            ...                      ...   
26703                          0.0                      0.0   
26704                          1.0                      1.0   
26705                          0.0                      0.0   
26706                          0.0                      1.0   
26707                          0.0                      0.0   

       behavioral_touch_face  ...         education      race     sex  \
0                        1.0  ...  College Graduate  Hispanic  Female   
1                        0.0  ...          12 Years     White    Male   
2                        1.0  ...  College Graduate     White    Male   
3                        0.0  ...          12 Years     White  Female   
4                        1.0  ...          12 Years     Black  Female   
...                      ...  ...               ...       ...     ...   
26703                    1.0  ...               NaN     White  Female   
26704                    1.0  ...          12 Years     White    Male   
26705                    0.0  ...      Some College     White  Female   
26706                    0.0  ...      Some College     White  Female   
26707                    1.0  ...  College Graduate     White  Female   

                  income_poverty  marital_status  rent_or_own  \
0                      > $75,000     Not Married         Rent   
1                  Below Poverty     Not Married         Rent   
2                      > $75,000         Married          Own   
3      <= $75,000, Above Poverty         Married          Own   
4      <= $75,000, Above Poverty     Not Married          Own   
...                          ...             ...          ...   
26703                        NaN             NaN        

In [510]:
x_test.set_index(['respondent_id'], inplace=True)

In [511]:
x_test

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
respondent_id                                                          
26707                  2.0            2.0                        0.0   
26708                  1.0            1.0                        0.0   
26709                  2.0            2.0                        0.0   
26710                  1.0            1.0                        0.0   
26711                  3.0            1.0                        1.0   
...                    ...            ...                        ...   
53410                  1.0            1.0                        0.0   
53411                  3.0            1.0                        0.0   
53412                  0.0            1.0                        0.0   
53413                  3.0            1.0                        0.0   
53414                  2.0            1.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
26707                           1.0                   0.0   
26708                           0.0                   0.0   
26709                           0.0                   1.0   
26710                           0.0                   0.0   
26711                           1.0                   0.0   
...                             ...                   ...   
53410                           1.0                   0.0   
53411                           1.0                   0.0   
53412                           0.0                   0.0   
53413                           1.0                   0.0   
53414                           0.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
26707                            1.0                          1.0   
26708                            0.0                          0.0   
26709                            1.0                          1.0   
26710                            0.0                          0.0   
26711                            1.0                          1.0   
...                              ...                          ...   
53410                            1.0                          0.0   
53411                            1.0                          1.0   
53412                            0.0                          0.0   
53413                            1.0                          0.0   
53414                            1.0                          0.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
26707                              0.0                    1.0   
26708                              0.0                    0.0   
26709                              1.0                    1.0   
26710                              0.0                    0.0   
26711                              1.0                    1.0   
...                                ...                    ...   
53410                              0.0                    1.0   
53411                              1.0                    1.0   
53412                              0.0                    0.0   
53413                              1.0                    0.0   
53414                              0.0                    1.0   

               doctor_recc_xyz  ...         education      race     sex  \
respondent_id                   ...                                       
26707                      0.0  ...  College Graduate  Hispanic  Female   
26708                      0.0  ...          12 Years     White    Male   
26709                      0.0  ...  College Graduate     White    Male   
26710                      1.0  ...          12 Years     White  Female   
26711                      0.0  ...          12 Years     Black  Female   
...            

In [512]:
x_test['rent_or_own']=le.fit_transform(x_test['rent_or_own'])

In [513]:
x_test['sex']=le.fit_transform(x_test['sex'])

In [514]:
x_test['age_group']=le.fit_transform(x_test['age_group'])

In [515]:
x_test['education']=le.fit_transform(x_test['education'])

In [516]:
x_test['race']=le.fit_transform(x_test['race'])

In [517]:
x_test['marital_status']=le.fit_transform(x_test['marital_status'])

In [518]:
x_test['employment_status']=le.fit_transform(x_test['employment_status'])

In [519]:
x_test['income_poverty']=le.fit_transform(x_test['income_poverty'])

In [520]:
x_test['census_msa']=le.fit_transform(x_test['census_msa'])

In [521]:
x_test['rent_or_own']=le.fit_transform(x_test['rent_or_own'])

In [522]:
x_test.columns

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'census_msa', 'household_adults',
       'household_children'],
      dtype='object')

In [523]:
x_test

xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
respondent_id                                                          
26707                  2.0            2.0                        0.0   
26708                  1.0            1.0                        0.0   
26709                  2.0            2.0                        0.0   
26710                  1.0            1.0                        0.0   
26711                  3.0            1.0                        1.0   
...                    ...            ...                        ...   
53410                  1.0            1.0                        0.0   
53411                  3.0            1.0                        0.0   
53412                  0.0            1.0                        0.0   
53413                  3.0            1.0                        0.0   
53414                  2.0            1.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
26707                           1.0                   0.0   
26708                           0.0                   0.0   
26709                           0.0                   1.0   
26710                           0.0                   0.0   
26711                           1.0                   0.0   
...                             ...                   ...   
53410                           1.0                   0.0   
53411                           1.0                   0.0   
53412                           0.0                   0.0   
53413                           1.0                   0.0   
53414                           0.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
26707                            1.0                          1.0   
26708                            0.0                          0.0   
26709                            1.0                          1.0   
26710                            0.0                          0.0   
26711                            1.0                          1.0   
...                              ...                          ...   
53410                            1.0                          0.0   
53411                            1.0                          1.0   
53412                            0.0                          0.0   
53413                            1.0                          0.0   
53414                            1.0                          0.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
26707                              0.0                    1.0   
26708                              0.0                    0.0   
26709                              1.0                    1.0   
26710                              0.0                    0.0   
26711                              1.0                    1.0   
...                                ...                    ...   
53410                              0.0                    1.0   
53411                              1.0                    1.0   
53412                              0.0                    0.0   
53413                              1.0                    0.0   
53414                              0.0                    1.0   

               doctor_recc_xyz  ...  education  race  sex  income_poverty  \
respondent_id                   ...                                         
26707                      0.0  ...          2     1    0               1   
26708                      0.0  ...          0     3    1               2   
26709                      0.0  ...          2     3    1               1   
26710                      1.0  ...          0     3    0               0   
26711                      0.0  ...          0     0    0               0   
.

In [524]:
imputer.fit(x_test)

SimpleImputer()

In [525]:
x_test=imputer.transform(x_test)

In [526]:
x_test

array([[2., 2., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 2., 3., 0.],
       [2., 2., 0., ..., 2., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [3., 1., 0., ..., 0., 1., 0.],
       [2., 1., 0., ..., 1., 0., 0.]])

In [527]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [528]:
x=sc.fit_transform(x)

In [529]:
x

array([[-0.68060883, -2.04692846, -0.22691136, ...,  1.4168754 ,
        -1.18217739, -0.57866659],
       [ 1.5202786 ,  1.19564718, -0.22691136, ..., -1.01237871,
        -1.18217739, -0.57866659],
       [-0.68060883, -0.42564064, -0.22691136, ..., -1.01237871,
         1.48489142, -0.57866659],
       ...,
       [ 0.41983489,  1.19564718, -0.22691136, ..., -1.01237871,
        -1.18217739, -0.57866659],
       [-0.68060883, -0.42564064, -0.22691136, ...,  1.4168754 ,
         0.15135701, -0.57866659],
       [-1.78105254, -2.04692846, -0.22691136, ...,  0.20224834,
         0.15135701, -0.57866659]])

In [530]:
x_test=sc.fit_transform(x_test)

In [531]:
x_test

array([[ 0.41812342,  1.19498678, -0.22889624, ..., -0.99277669,
         0.14072438, -0.58398583],
       [-0.69138518, -0.43315438, -0.22889624, ...,  1.44438309,
         2.80367814, -0.58398583],
       [ 0.41812342,  1.19498678, -0.22889624, ...,  1.44438309,
         0.14072438, -0.58398583],
       ...,
       [-1.80089377, -0.43315438, -0.22889624, ..., -0.99277669,
         0.14072438, -0.58398583],
       [ 1.52763201, -0.43315438, -0.22889624, ..., -0.99277669,
         0.14072438, -0.58398583],
       [ 0.41812342, -0.43315438, -0.22889624, ...,  0.2258032 ,
        -1.1907525 , -0.58398583]])

In [532]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x,y1)

LogisticRegression()

In [533]:
y1_pred=classifier.predict_proba(x_test)

In [534]:
y1_pred

array([[0.76054352, 0.23945648],
       [0.97035702, 0.02964298],
       [0.3181623 , 0.6818377 ],
       ...,
       [0.74738425, 0.25261575],
       [0.59483371, 0.40516629],
       [0.40353469, 0.59646531]])

In [535]:
y1_pred=y1_pred[:,1]

In [536]:
y1_pred

array([0.23945648, 0.02964298, 0.6818377 , ..., 0.25261575, 0.40516629,
       0.59646531])

In [537]:
classifier.fit(x,y2)

LogisticRegression()

In [538]:
y2_pred=classifier.predict_proba(x_test)

In [539]:
y2_pred

array([[0.91411791, 0.08588209],
       [0.98107201, 0.01892799],
       [0.56163636, 0.43836364],
       ...,
       [0.83636599, 0.16363401],
       [0.94878908, 0.05121092],
       [0.37292008, 0.62707992]])

In [540]:
y2_pred=y2_pred[:,1]

In [541]:
y2_pred

array([0.08588209, 0.01892799, 0.43836364, ..., 0.16363401, 0.05121092,
       0.62707992])

In [542]:
y1_pred

array([0.23945648, 0.02964298, 0.6818377 , ..., 0.25261575, 0.40516629,
       0.59646531])

In [417]:
from sklearn.svm import SVC
sv=SVC(kernel='linear',probability=True)

In [418]:
sv.fit(x,y1)

SVC(kernel='linear', probability=True)

In [419]:
y1_pre=sv.predict_proba(x_test)

In [420]:
y1_pre

array([[0.7778079 , 0.2221921 ],
       [0.96517929, 0.03482071],
       [0.32690921, 0.67309079],
       ...,
       [0.75494892, 0.24505108],
       [0.57822977, 0.42177023],
       [0.42613649, 0.57386351]])

In [421]:
y1_pre=y1_pre[:,1]

In [422]:
y1_pre

array([0.2221921 , 0.03482071, 0.67309079, ..., 0.24505108, 0.42177023,
       0.57386351])

In [423]:
sv.fit(x,y2)

SVC(kernel='linear', probability=True)

In [424]:
y2_pre=sv.predict_proba(x_test)

In [425]:
y2_pre

array([[0.90906097, 0.09093903],
       [0.98299804, 0.01700196],
       [0.65441243, 0.34558757],
       ...,
       [0.83202936, 0.16797064],
       [0.94251497, 0.05748503],
       [0.3394344 , 0.6605656 ]])

In [426]:
y2_pre=y2_pre[:,1]

In [427]:
y2_pre

array([0.09093903, 0.01700196, 0.34558757, ..., 0.16797064, 0.05748503,
       0.6605656 ])

In [428]:
from sklearn.svm import SVC
sv=SVC(kernel='rbf',probability=True)

In [429]:
sv.fit(x,y1)

SVC(probability=True)

In [430]:
y1_p=sv.predict_proba(x_test)

In [431]:
y1_p

array([[0.8265556 , 0.1734444 ],
       [0.86683505, 0.13316495],
       [0.27437663, 0.72562337],
       ...,
       [0.83164099, 0.16835901],
       [0.54183501, 0.45816499],
       [0.2601602 , 0.7398398 ]])

In [432]:
y1_p=y1_p[:,1]

In [552]:
sv.fit(x,y2)

SVC(probability=True)

In [434]:
y2_p=sv.predict_proba(x_test)

In [435]:
y2_p

array([[0.91548715, 0.08451285],
       [0.86929836, 0.13070164],
       [0.76309116, 0.23690884],
       ...,
       [0.87306509, 0.12693491],
       [0.96815541, 0.03184459],
       [0.42729257, 0.57270743]])

In [436]:
y2_p=y2_p[:,1]

In [437]:
y2_p

array([0.08451285, 0.13070164, 0.23690884, ..., 0.12693491, 0.03184459,
       0.57270743])

In [438]:
from sklearn.naive_bayes import GaussianNB

In [439]:
gnb=GaussianNB()

In [440]:
gnb.fit(x,y1)

GaussianNB()

In [441]:
y1_predict=gnb.predict_proba(x_test)

In [442]:
y1_predict

array([[8.52318870e-01, 1.47681130e-01],
       [9.99999961e-01, 3.87047996e-08],
       [4.44586716e-03, 9.95554133e-01],
       ...,
       [9.90296426e-01, 9.70357445e-03],
       [5.06861209e-01, 4.93138791e-01],
       [9.23742260e-02, 9.07625774e-01]])

In [443]:
gnb.fit(x,y2)

GaussianNB()

In [444]:
y2_predict=gnb.predict_proba(x_test)

In [445]:
y2_predict

array([[9.84609215e-01, 1.53907848e-02],
       [9.99997241e-01, 2.75949156e-06],
       [2.76677546e-02, 9.72332245e-01],
       ...,
       [9.98417764e-01, 1.58223618e-03],
       [9.41089439e-01, 5.89105610e-02],
       [4.48323763e-01, 5.51676237e-01]])

In [446]:
y1_predict

array([[8.52318870e-01, 1.47681130e-01],
       [9.99999961e-01, 3.87047996e-08],
       [4.44586716e-03, 9.95554133e-01],
       ...,
       [9.90296426e-01, 9.70357445e-03],
       [5.06861209e-01, 4.93138791e-01],
       [9.23742260e-02, 9.07625774e-01]])

In [447]:
y1_pred

array([0.23945648, 0.02964298, 0.6818377 , ..., 0.25261575, 0.40516629,
       0.59646531])

In [448]:
y1_pre

array([0.2221921 , 0.03482071, 0.67309079, ..., 0.24505108, 0.42177023,
       0.57386351])

In [449]:
y1_p

array([0.1734444 , 0.13316495, 0.72562337, ..., 0.16835901, 0.45816499,
       0.7398398 ])

In [450]:
y2_pred

array([0.08588209, 0.01892799, 0.43836364, ..., 0.16363401, 0.05121092,
       0.62707992])

In [451]:
y2_pre

array([0.09093903, 0.01700196, 0.34558757, ..., 0.16797064, 0.05748503,
       0.6605656 ])

In [452]:
y2_p

array([0.08451285, 0.13070164, 0.23690884, ..., 0.12693491, 0.03184459,
       0.57270743])

In [453]:
y2_predict

array([[9.84609215e-01, 1.53907848e-02],
       [9.99997241e-01, 2.75949156e-06],
       [2.76677546e-02, 9.72332245e-01],
       ...,
       [9.98417764e-01, 1.58223618e-03],
       [9.41089439e-01, 5.89105610e-02],
       [4.48323763e-01, 5.51676237e-01]])

In [454]:
y1_predict

array([[8.52318870e-01, 1.47681130e-01],
       [9.99999961e-01, 3.87047996e-08],
       [4.44586716e-03, 9.95554133e-01],
       ...,
       [9.90296426e-01, 9.70357445e-03],
       [5.06861209e-01, 4.93138791e-01],
       [9.23742260e-02, 9.07625774e-01]])

In [548]:
vaccinations=pd.DataFrame(y1_pred,y2_pred)

In [549]:
vaccinations.to_csv('vaccination.csv')

In [550]:
y1_pred

array([0.23945648, 0.02964298, 0.6818377 , ..., 0.25261575, 0.40516629,
       0.59646531])

In [551]:
y2_pred

array([0.08588209, 0.01892799, 0.43836364, ..., 0.16363401, 0.05121092,
       0.62707992])